### ISSUE TITLE
Does this package still works ? [Vite] [React18]

### ISSUE THREAD

**Issue by 0xbuidler** [AndrzejSala/use-scroll-direction#36]
Hello, i'm trying to use this package with Vite and React 18 but it doesn't work. (I'm using it with the window object)

**Comment by 0xbuidler** [comment]
Update. It works.

**Comment by AndrzejSala** [comment]
@sshmaxime 

Great to hear that.
If you have any ideas on how to make docs more clear or make the hook usage more convenient I'll be glad to help.
